#!/bin/bash

echo "🔧 Adding environment variables to Vercel..."
echo ""
echo "Please add these 3 variables manually in Vercel Dashboard:"
echo ""
echo "📍 Open: https://vercel.com/bests-projects-b62d7e64/y/settings/environment-variables"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 1:"
echo "  Name:  NEXT_PUBLIC_SUPABASE_URL"
echo "  Value: https://mtxhzvxetxcppzwgrrsu.supabase.co"
echo "  ✓ Development"
echo "  ✓ Preview"
echo "  ✓ Production"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 2:"
echo "  Name:  NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "  Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eGh6dnhldHhjcHB6d2dycnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzQwMzksImV4cCI6MjA1ODE1MDAzOX0.sb_publishable_VMpe_gI4NH06Db9_FOeOJw_D4cLLrg7"
echo "  ✓ Development"
echo "  ✓ Preview"
echo "  ✓ Production"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Variable 3:"
echo "  Name:  SUPABASE_SERVICE_ROLE_KEY"
echo "  Value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10eGh6dnhldHhjcHB6d2dycnN1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjU3NDAzOSwiZXhwIjoyMDU4MTUwMDM5fQ.uhp1LaIc91VDJRjFVAGP8Q_V2sM9XOX"
echo "  ✓ Development"
echo "  ✓ Preview"
echo "  ✓ Production"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After adding all variables:"
echo "  1. Click 'Save'"
echo "  2. Run: vercel --prod"
echo "  3. Open: https://y-phi-black.vercel.app/check"
echo ""
