#!/bin/bash

echo "Adding environment variables to Vercel..."
echo ""
echo "======================================"
echo "PLEASE ADD THESE IN VERCEL DASHBOARD:"
echo "======================================"
echo ""
echo "URL: https://vercel.com/bests-projects-b62d7e64/blog/settings/environment-variables"
echo ""
echo "Variable 1:"
echo "  Name: NEXT_PUBLIC_SUPABASE_URL"
echo "  Value: https://mtxhzvxetxcppzwgrrsu.supabase.co"
echo "  Environments: Production, Preview, Development"
echo ""
echo "Variable 2:"
echo "  Name: SUPABASE_SERVICE_ROLE_KEY"
echo "  Value: [Your Service Role Key from Supabase Dashboard]"
echo "  Environments: Production, Preview, Development"
echo ""
echo "======================================"
echo "Then run: vercel --prod"
echo "======================================"
