-- TEMPORARY: Disable RLS for testing
-- Execute this in Supabase SQL Editor to test without RLS

ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE channels DISABLE ROW LEVEL SECURITY;
ALTER TABLE channel_editors DISABLE ROW LEVEL SECURITY;
ALTER TABLE news DISABLE ROW LEVEL SECURITY;
ALTER TABLE news_channels DISABLE ROW LEVEL SECURITY;
